


title: "Module 5 — Data Story Site"


author: Byron Portillo



navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
    - Getting Started: "getstarted"     
  Table Demo: "table-demo"              
  Author's home: "https://deanattali.com"

# --- Logo --- #


avatar: "/assets/img/asu-avatar.jpg"
round-avatar: true

title-img: "/assets/img/asu-avatar.jpg"



# --- Footer social media links --- #

social-network-links:
  email: "bjportil@asu.edu"
  github: "Portillousmc07"
  linkedin: "byronportillo"
  twitter: "fubar3824"

# RSS description shows an RSS link in the footer if present
rss-description: 

# --- General options --- #

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "ByronPortillo.com/clean"

excerpt_length: 40        # shorter summaries on blog feed
feed_show_excerpt: true
feed_show_tags: true

post_search: true         # enable search in the navbar

# --- Colours / background image --- #

# Maroon: #8C1D40   Gold: #FFC627   Dark Maroon: #6E1632

navbar-col: "#8C1D40"       
navbar-text-col: "#FFFFFF"  
navbar-border-col: "#6E1632"

page-col: "#FFFFFF"         
text-col: "#1F1F1F"         

link-col: "#8C1D40"        
hover-col: "#FFC627"        

footer-col: "#8C1D40"       
footer-text-col: "#FFFFFF"  
footer-link-col: "#FFC627"  

mobile-theme-col: "#8C1D40" 


# mobile-theme-col: "#0066CC"

# --- Custom CSS/JS (optional) --- #
# site-css:
#   - "/assets/css/custom-styles.css"
# site-js:
#   - "/assets/js/custom-script.js"

# --- Analytics (leave blank for now) --- #
# gtag: ""
# google_analytics: ""
# cloudflare_analytics: ""
# gtm: ""

# --- Comments (disabled for now) --- #
# disqus: ""
# fb_comment_id: ""
# utterances:
#   repository: "Portillousmc07/portillousmc07.github.io"
#   issue-term: title
#   theme: github-light
#   label: blog-comments

# --- Misc --- #

date_format: "%B %-d, %Y"
timezone: "America/Chicago"

# --- Jekyll settings --- #

markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap


