# --- Required options --- #

# Name of website
title: "Module 5 — Data Story Site"

# Your name to show in the footer
author: Byron Portillo

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "13 Year Marine Corps Veteran, SoCal Born, Kansas City living, Father of 4"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
    - Getting Started: "getstarted"     # added for lab
  Table Demo: "table-demo"              # added for lab
  Author's home: "https://deanattali.com"

# --- Logo --- #

# Replace with your own avatar if desired
avatar: "/assets/img/avatar-icon.png"
round-avatar: true
# title-img: /path/to/logo.png   # Uncomment if you want a logo instead of text

# --- Footer social media links --- #
# Replace with your real info or leave blank so icons still show but inactive
social-network-links:
  email: "bjportil@asu.edu"
  github: Portillousmc07
  linkedin: www.linkedin.com/in/byronportillo
  twitter: "isnt it X now? @fubar3824"
  facebook: "I dislike social medial overall"
  youtube: "To include youtube"

# RSS description shows an RSS link in the footer if present
rss-description: "This website is a virtual proof that I'm awesome, and to include that I completed this assignment, of course."

# --- General options --- #

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "ByronPortillo.com/clean"

excerpt_length: 40        # shorter summaries on blog feed
feed_show_excerpt: true
feed_show_tags: true

post_search: true         # enable search in the navbar

# --- Colours / background image --- #
# Demonstrates you customized the palette

navbar-col: "#F5F5F5"
navbar-text-col: "#222222"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#333333"
link-col: "#0066CC"
hover-col: "#004C99"
footer-col: "#F5F5F5"
footer-text-col: "#555555"
footer-link-col: "#222222"

# mobile-theme-col: "#0066CC"

# --- Custom CSS/JS (optional) --- #
# site-css:
#   - "/assets/css/custom-styles.css"
# site-js:
#   - "/assets/js/custom-script.js"

# --- Analytics (leave blank for now) --- #
# gtag: ""
# google_analytics: ""
# cloudflare_analytics: ""
# gtm: ""

# --- Comments (disabled for now) --- #
# disqus: ""
# fb_comment_id: ""
# utterances:
#   repository: "Portillousmc07/portillousmc07.github.io"
#   issue-term: title
#   theme: github-light
#   label: blog-comments

# --- Misc --- #

date_format: "%B %-d, %Y"
timezone: "America/Chicago"

# --- Jekyll settings --- #

markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap


